In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [52]:
#lire la dataset
dataset = pd.read_csv('50_Startups.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset.head(10)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [53]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [54]:
#Modifer les valeurs categoriel en nombre

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
#on supprime la premiere colone pour eviter la colinearité
x = x[:, 1:]
x

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7, 153514.11, 0.0],
       [0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [0.0, 1.0, 78389.47, 153773.43, 299737.29],
       [1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [1.0, 0.0, 67532.53, 105751.03, 304768.73],
       [0.0, 1.0, 77044.01, 99281.34, 140574.81],
       [0.0, 0.0, 64664.71, 139553.16, 137962.62],
       [1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [1.0, 0.0, 28663.76, 127056.21, 201126.82],
       [0.0, 0.0, 44069.95, 51283.14, 197029.42],
       [0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [0.0, 0.0, 38558.51, 82982.09, 174999.3],
       [0.0, 0.0, 28754.33, 118546.05, 172795.67],
       [1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [0.0, 0.0, 23640.93, 96189.63, 148001.11],
       [0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [0.0, 0.0, 22177.74, 154806.14, 28334.72],
       [0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [0.0, 0.0, 0.0, 135426.92, 0.0],
       [0.0, 1.0, 542.05, 51743.15, 0.0],
       [0.0, 0.0, 0.0, 116983.8, 45173.06]], dtype=object)

In [55]:
#Diviser en Test Set et Training Set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25 , random_state=0)

In [56]:
#construction ou entrainer le model

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [57]:
y_pred = regressor.predict(x_test)
y_pred

array([104440.72582616, 132253.81567698, 132872.07174272,  71707.78771428,
       178678.9934985 , 115078.13124331,  66093.9297267 ,  98759.7276409 ,
       114113.5994088 , 167979.49411476,  95786.77295823,  87785.3497979 ,
       110455.98228344])

In [58]:
dfFinal = pd.DataFrame({'Real Values':y_test, 'Predicted Values': y_pred})
dfFinal

    Real Values  Predicted Values
0     103282.38     104440.725826
1     144259.40     132253.815677
2     146121.95     132872.071743
3      77798.83      71707.787714
4     191050.39     178678.993499
5     105008.31     115078.131243
6      81229.06      66093.929727
7      97483.56      98759.727641
8     110352.25     114113.599409
9     166187.94     167979.494115
10     96778.92      95786.772958
11     96479.51      87785.349798
12    105733.54     110455.982283

In [60]:
#on test une valeur au hasard
regressor.predict(np.array([[1, 0, 130000, 140000, 300000]]))

array([158530.49543736])

In [61]:
# On Verifie la precision 

from sklearn import metrics
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

8591.234654128659